# Generated by Django 5.1.4 on 2026-02-25 19:02

import apps.core.storage
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_pgvector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('pncp', 'PNCP'), ('compras_gov', 'Compras.gov.br'), ('manual', 'Cadastro Manual')], db_index=True, max_length=20, verbose_name='Fonte')),
                ('external_id', models.CharField(help_text='ID original na fonte', max_length=200, verbose_name='ID externo')),
                ('dedup_hash', models.CharField(help_text='SHA-256 de source:external_id para idempotência', max_length=64, unique=True, verbose_name='Hash de dedup')),
                ('object_hash', models.CharField(db_index=True, help_text='SHA-256 do objeto normalizado para dedup cross-source', max_length=64, verbose_name='Hash do objeto')),
                ('title', models.TextField(verbose_name='Objeto da contratação')),
                ('description', models.TextField(blank=True, verbose_name='Informação complementar')),
                ('modality', models.CharField(choices=[('pregao_eletronico', 'Pregão Eletrônico'), ('pregao_presencial', 'Pregão Presencial'), ('concorrencia_eletronica', 'Concorrência Eletrônica'), ('concorrencia_presencial', 'Concorrência Presencial'), ('dispensa', 'Dispensa de Licitação'), ('inexigibilidade', 'Inexigibilidade'), ('concurso', 'Concurso'), ('leilao', 'Leilão'), ('dialogo_competitivo', 'Diálogo Competitivo'), ('credenciamento', 'Credenciamento'), ('other', 'Outra')], default='other', max_length=30, verbose_name='Modalidade')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Número da compra')),
                ('process_number', models.CharField(blank=True, max_length=100, verbose_name='Nº do processo')),
                ('entity_cnpj', models.CharField(db_index=True, max_length=18, verbose_name='CNPJ do órgão')),
                ('entity_name', models.CharField(max_length=400, verbose_name='Nome do órgão')),
                ('entity_uf', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='UF')),
                ('entity_city', models.CharField(blank=True, max_length=200, verbose_name='Município')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Publicação')),
                ('proposals_open_at', models.DateTimeField(blank=True, null=True, verbose_name='Abertura de propostas')),
                ('proposals_close_at', models.DateTimeField(blank=True, null=True, verbose_name='Encerramento de propostas')),
                ('deadline', models.DateTimeField(blank=True, db_index=True, help_text='Data-limite para participação/entrega', null=True, verbose_name='Prazo final')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor estimado')),
                ('awarded_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor homologado')),
                ('is_srp', models.BooleanField(default=False, verbose_name='SRP (Registro de preço)')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Dados brutos da API')),
                ('link', models.URLField(blank=True, verbose_name='Link no sistema de origem')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('analyzing', 'Em Análise'), ('eligible', 'Apto'), ('discarded', 'Descartado'), ('submitted', 'Proposta Enviada')], db_index=True, default='new', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='idx_source_extid'), models.Index(fields=['entity_uf', 'status'], name='idx_uf_status'), models.Index(fields=['deadline', 'status'], name='idx_deadline_status')],
            },
        ),
        migrations.CreateModel(
            name='ExtractedRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('fiscal', 'Habilitação Fiscal'), ('juridica', 'Habilitação Jurídica'), ('tecnica', 'Qualificação Técnica'), ('economica', 'Qualificação Econômico-Financeira'), ('general', 'Requisito Geral')], max_length=20, verbose_name='Categoria')),
                ('requirement', models.TextField(verbose_name='Requisito')),
                ('evidence', models.JSONField(default=dict, help_text='{"source": "api|document", "excerpt": "...", "page": 3, "confidence": 0.95}', verbose_name='Evidência')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Requisito Extraído',
                'verbose_name_plural': 'Requisitos Extraídos',
            },
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_type', models.CharField(choices=[('summary', 'Resumo Executivo'), ('checklist', 'Checklist de Habilitação'), ('risks', 'Riscos e Pegadinhas'), ('full', 'Análise Completa')], max_length=20, verbose_name='Tipo')),
                ('content', models.JSONField(help_text='JSON com resumo, checklist, riscos — conforme analysis_type', verbose_name='Conteúdo')),
                ('prompt_version', models.CharField(max_length=50, verbose_name='Versão do prompt')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo IA')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens consumidos')),
                ('processing_time_ms', models.PositiveIntegerField(default=0, verbose_name='Tempo (ms)')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Resumo IA',
                'verbose_name_plural': 'Resumos IA',
            },
        ),
        migrations.CreateModel(
            name='OpportunityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(verbose_name='URL original')),
                ('file', models.FileField(blank=True, upload_to=apps.core.storage.document_upload_path, verbose_name='Arquivo local')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256')),
                ('file_name', models.CharField(blank=True, max_length=500, verbose_name='Nome do arquivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('doc_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo')),
                ('processing_status', models.CharField(choices=[('pending', 'Pendente'), ('downloading', 'Baixando'), ('downloaded', 'Baixado'), ('extracting', 'Extraindo texto'), ('indexed', 'Indexado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texto extraído')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Páginas')),
                ('ocr_used', models.BooleanField(default=False, verbose_name='OCR utilizado')),
                ('error_message', models.TextField(blank=True, verbose_name='Erro')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Documento da Oportunidade',
                'verbose_name_plural': 'Documentos da Oportunidade',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField(verbose_name='Índice do chunk')),
                ('content', models.TextField(verbose_name='Conteúdo do chunk')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Página')),
                ('token_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tokens')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True, verbose_name='Embedding')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='opportunities.opportunitydocument')),
            ],
            options={
                'verbose_name': 'Chunk de Documento',
                'verbose_name_plural': 'Chunks de Documentos',
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='idx_chunk_doc_idx')],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
        migrations.CreateModel(
            name='OpportunityItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_number', models.PositiveIntegerField(verbose_name='Nº do item')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Quantidade')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unidade')),
                ('estimated_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Preço unitário estimado')),
                ('estimated_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor total estimado')),
                ('material_or_service', models.CharField(blank=True, max_length=20, verbose_name='Material/Serviço')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Dados brutos')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Item da Oportunidade',
                'verbose_name_plural': 'Itens da Oportunidade',
                'ordering': ['item_number'],
                'unique_together': {('opportunity', 'item_number')},
            },
        ),
    ]
