# Generated by Django 5.1.4 on 2026-02-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Informação complementar'),
        ),
    ]
