# Generated by Django 5.1.4 on 2026-02-25 19:40

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Embedding'),
        ),
    ]
