# Generated by Django 5.1.4 on 2026-02-26 02:38

import logging

import pgvector.django.vector
from django.db import migrations, transaction

logger = logging.getLogger(__name__)


def try_alter_vector_3072(apps, schema_editor):
    try:
        with transaction.atomic(using=schema_editor.connection.alias):
            schema_editor.execute(
                "ALTER TABLE opportunities_documentchunk "
                "ALTER COLUMN embedding TYPE vector(3072) USING embedding::vector(3072);"
            )
    except Exception as e:
        logger.warning("Skipping embedding ALTER to vector(3072): %s", e)


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_change_embedding_768'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='documentchunk',
                    name='embedding',
                    field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True, verbose_name='Embedding'),
                ),
            ],
            database_operations=[
                migrations.RunPython(try_alter_vector_3072, migrations.RunPython.noop),
            ],
        ),
    ]
