# Generated by Django 5.1.4 on 2026-02-26 02:38

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_change_embedding_768'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True, verbose_name='Embedding'),
        ),
    ]
