# Generated by Django 5.1.4 on 2026-02-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_backfill_entity_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='link',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Link no sistema de origem'),
        ),
    ]
