# Generated by Django 5.1.4 on 2026-02-25 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(help_text='0 = sem aderência, 100 = perfeito', verbose_name='Score (0-100)')),
                ('justification', models.TextField(verbose_name='Justificativa do score')),
                ('missing_docs', models.JSONField(default=list, help_text='[{"type": "atestado_tecnico", "reason": "..."}]', verbose_name='Documentos faltantes')),
                ('missing_capabilities', models.JSONField(default=list, verbose_name='Competências faltantes')),
                ('evidence', models.JSONField(default=list, help_text='Lista de evidências usadas no matching', verbose_name='Evidências')),
                ('prompt_version', models.CharField(max_length=50, verbose_name='Versão do prompt')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo IA')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='clients.client')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-score'],
                'unique_together': {('opportunity', 'client')},
            },
        ),
    ]
