# Generated by Django 5.1.4 on 2026-02-25 19:02

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('trade_name', models.CharField(blank=True, max_length=300, verbose_name='Nome Fantasia')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text='Lista de UFs (ex: SP, RJ, MG)', size=None, verbose_name='UFs de interesse')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Palavras-chave do catálogo/serviços', size=None, verbose_name='Palavras-chave')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Categorias de serviço/produto')),
                ('min_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margem mínima (%)')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor máximo de contrato')),
                ('logistics_reach', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, size=None, verbose_name='Alcance logístico (UFs)')),
                ('restrictions', models.TextField(blank=True, verbose_name='Restrições')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notify_email', models.BooleanField(default=True, verbose_name='Notificar por e-mail')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('cnd_federal', 'CND Federal'), ('cnd_estadual', 'CND Estadual'), ('cnd_municipal', 'CND Municipal'), ('fgts', 'CRF/FGTS'), ('cndt', 'CNDT (Trabalhista)'), ('balanco', 'Balanço Patrimonial'), ('atestado_tecnico', 'Atestado Técnico'), ('contrato_social', 'Contrato Social'), ('procuracao', 'Procuração'), ('sicaf', 'SICAF'), ('other', 'Outro')], max_length=30, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('file', models.FileField(blank=True, upload_to='client_docs/%Y/%m/', verbose_name='Arquivo')),
                ('url', models.URLField(blank=True, verbose_name='URL externa')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('status', models.CharField(choices=[('valid', 'Válido'), ('expiring', 'A vencer (< 30 dias)'), ('expired', 'Vencido'), ('pending', 'Pendente')], default='pending', max_length=20, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
            ],
            options={
                'verbose_name': 'Documento do Cliente',
                'verbose_name_plural': 'Documentos do Cliente',
            },
        ),
    ]
