# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="notify_whatsapp",
            field=models.BooleanField(
                default=False, verbose_name="Notificar por WhatsApp"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="whatsapp_phone",
            field=models.CharField(
                blank=True,
                help_text="Formato: 5511999999999 (DDI+DDD+numero)",
                max_length=20,
                verbose_name="WhatsApp",
            ),
        ),
    ]
