# Generated by Django 5.1.4 on 2026-02-25 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('new_opportunity', 'Nova Oportunidade'), ('high_score_match', 'Match com score alto'), ('deadline_warning', 'Prazo crítico'), ('ai_complete', 'Análise IA concluída'), ('document_ready', 'Documento processado'), ('ingestion_error', 'Erro de ingestão')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('webhook', 'Webhook'), ('internal', 'Interno (dashboard)')], default='internal', max_length=20, verbose_name='Canal')),
                ('recipient', models.CharField(blank=True, max_length=300, verbose_name='Destinatário')),
                ('subject', models.CharField(max_length=300, verbose_name='Assunto')),
                ('body', models.TextField(verbose_name='Corpo')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload extra')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status de entrega')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('error_message', models.TextField(blank=True, verbose_name='Erro')),
                ('opportunity_id', models.UUIDField(blank=True, null=True, verbose_name='Oportunidade')),
                ('client_id', models.UUIDField(blank=True, null=True, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
    ]
